### ISSUE TITLE
Merge Request?

### ISSUE THREAD

**Issue by kylecribbs** [SLiX69/Sonarr-API-Python-Wrapper#3]
Are you accepting merge request (pull request)? Or should i just fork.

**Comment by bnorquist** [comment]
The owner has merged a few PRs in the past. I would recommend forking and opening a PR once you have tested your change.

**Comment by kylecribbs** [comment]
Submitted Pull Request

**Comment by kylecribbs** [comment]
Any update?

**Comment by kylecribbs** [comment]
Its been almost 3 weeks. Hard forking: 
https://github.com/kylecribbs/arr

**Comment by SLiX69** [comment]
@kylecribbs 
Hi, sorry about the late reply. Didn't had much time the last months and disabled the notifications. 
I accept PRs. If you want to reopen it, I'll review it.

**Comment by kylecribbs** [comment]
I decided to open a new repo; especially since this repo tailors mainly towards Sonarr.. I am planning on making a sonarr/radarr wrapper

Please feel free to contribute

**Comment by SLiX69** [comment]
@kylecribbs 
Would you set note (w link) in your new repo (readme), that you forked this?

**Comment by SLiX69** [comment]
@kylecribbs ping

**Comment by kylecribbs** [comment]
@SLiX69 Sure, you could always do a pull request with an updated readme. But i will update
